// 尺寸 Token

export class AppRadius {
  static readonly small: number = 10;
  static readonly medium: number = 14;
  static readonly large: number = 22;
  static readonly card: number = 18;
  static readonly hero: number = 24;
  static readonly pill: number = 999;
}

export class AppSpacing {
  static readonly xs: number = 4;
  static readonly sm: number = 8;
  static readonly md: number = 12;
  static readonly lg: number = 16;
  static readonly xl: number = 24;
  static readonly xxl: number = 32;
}

export class AppElevation {
  static readonly card: number = 12;
  static readonly hero: number = 18;
  static readonly button: number = 18;
}
